apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cnpg.io/nodeSerial: "2"
    cnpg.io/operatorVersion: 1.30.0
    cnpg.io/pvcStatus: ready
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2026-08-11T05:03:00Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: cloudnative-pg
    app.kubernetes.io/name: postgresql
    cnpg.io/cluster: aims-postgres-cnpg
    cnpg.io/instanceName: aims-postgres-cnpg-2
    cnpg.io/instanceRole: replica
    cnpg.io/pvcRole: PG_DATA
    role: replica
  name: aims-postgres-cnpg-2
  namespace: production
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: Cluster
    name: aims-postgres-cnpg
    uid: 52b12eb6-e786-4c6c-bb3e-cd3d6a0219e6
  resourceVersion: "90271809"
  uid: 36637468-a12f-4318-884e-7bbdd28b4f9f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-36637468-a12f-4318-884e-7bbdd28b4f9f
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
