apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - detector-config.yaml
  - baseline-target-workloads.yaml
  - production-loadgens.yaml
  - tetragon-targeted-policies.yaml
